default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['pg_user'] %>
  password: <%= ENV['pg_pass'] %>
  host: <%= ENV['pg_host'] %>
  port: <%= ENV['pg_port'] %> 

development:
  <<: *default
  database: shopping_list_development

test:
  <<: *default
  database: shopping_list_test

production:
  <<: *default
  database: shopping_list_production
  username: shopping_list
  password: <%= ENV['SHOPPING_LIST_DATABASE_PASSWORD'] %>
